// Common JS, every file is module (by default)
//Modules - Encapsukated Code (only share minimum)
const names = require('./names')
const sayHey = require('./utis')
const data = require ('./alternatvee')
require('./mind-grenade')
console.log(data)
sayHey('Adam')
sayHey(names.john)
sayHey(names.peter)